=== andrecunha/BandexView/WebContent/restaurante.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

    <!-- é necessário? xmlns:rest="http://www.pcasc.usp.br/restaurante" -->
	<xsd:simpleType name="typeDate">
		<xsd:restriction base="xsd:string">
            <!-- (whitespaces)* dd/mm/yyyy (whitespaces)* -->
            <!-- alterei pra o mínimo de espaços e funciona com o xml da internet -->
			<xsd:pattern value="(\s)\d{2}/\d{2}/\d{4}" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:group name="nonEmptyMeal">
		<xsd:sequence>
			<xsd:element name="salada" type="xsd:string" />
			<xsd:element name="principal" type="xsd:string" />
			<xsd:element name="acompanhamento" type="xsd:string" />
			<xsd:element name="sobremesa" type="xsd:string" />
		</xsd:sequence>
	</xsd:group>

	<xsd:complexType name="meal">
		<xsd:choice>
			<xsd:element name="vazio" fixed="" />
			<xsd:group ref="nonEmptyMeal"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="weekDayMenu">
		<xsd:sequence>
			<xsd:element name="data" type="typeDate" />
			<xsd:element name="almoco" type="meal" />
			<xsd:element name="jantar" type="meal" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="restaurantType">
		<xsd:sequence>
			<xsd:element name="segunda" type="weekDayMenu" />
			<xsd:element name="terca" type="weekDayMenu" />
			<xsd:element name="quarta" type="weekDayMenu" />
			<xsd:element name="quinta" type="weekDayMenu" />
			<xsd:element name="sexta" type="weekDayMenu" />
			<xsd:element name="sabado" type="weekDayMenu" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="restaurante" type="restaurantType" />

</xsd:schema>

=== andrecunha/BandexView/WebContent/restaurante.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="restaurante.xsl"?>
<restaurante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:noNamespaceSchemaLocation="restaurante.xsd">
	<segunda>
		<data> 21/11/2011</data>
		<almoco>
			<salada>Saladas diversas</salada>
			<principal>Carne moída refogada</principal>
			<acompanhamento>Macarrão aos quatro queijos</acompanhamento>
			<sobremesa>Barra de Cereal e laranja</sobremesa>
		</almoco>
		<jantar>
			<salada>Saladas diversas</salada>
			<principal>Lingüiça à portuguesa</principal>
			<acompanhamento>Couve refogada</acompanhamento>
			<sobremesa>Abacaxi e laranja</sobremesa>
		</jantar>
	</segunda>
	<terca>
		<data> 22/11/2011</data>
		<almoco>
			<salada>Saladas diversas</salada>
			<principal>Lagarto à escabech</principal>
			<acompanhamento>Maionese de atum</acompanhamento>
			<sobremesa>Maçã e laranja</sobremesa>
		</almoco>
		<jantar>
			<salada>Saladas diversas</salada>
			<principal>Steak de frango</principal>
			<acompanhamento>Creme de milho</acompanhamento>
			<sobremesa>Melão e laranja</sobremesa>
		</jantar>
	</terca>
	<quarta>
		<data> 23/11/2011</data>
		<almoco>
			<salada>Saladas diversas</salada>
			<principal>Lombo à Califórnia</principal>
			<acompanhamento>Farofa</acompanhamento>
			<sobremesa>Mamão e laranja</sobremesa>
		</almoco>
		<jantar>
			<salada>Saladas diversas</salada>
			<principal>Picadinho de carne</principal>
			<acompanhamento>Suflê de abobrinha</acompanhamento>
			<sobremesa>Gelatina com creme e laranja</sobremesa>
		</jantar>
	</quarta>
	<quinta>
		<data> 24/11/2011</data>
		<almoco>
			<salada>Saladas diversas</salada>
			<principal>Strogonoff de frango</principal>
			<acompanhamento>Batata corada</acompanhamento>
			<sobremesa>Brigadeirão e laranja</sobremesa>
		</almoco>
		<jantar>
			<salada>Saladas diversas</salada>
			<principal>Hambúrguer</principal>
			<acompanhamento>Ervilha à parmetier</acompanhamento>
			<sobremesa>Arroz doce com canela e laranja</sobremesa>
		</jantar>
	</quinta>
	<sexta>
		<data> 25/11/2011</data>
		<almoco>
			<salada>Saladas diversas</salada>
			<principal>Bife ao molho de moyashi</principal>
			<acompanhamento>Polenta frita</acompanhamento>
			<sobremesa>Arroz com açafrão</sobremesa>
		</almoco>
		<jantar>
			<salada>Saladas diversas</salada>
			<principal>Panqueca de carne</principal>
			<acompanhamento>Acelga ao bacon</acompanhamento>
			<sobremesa>Banana caramelada e laranja</sobremesa>
		</jantar>
	</sexta>
	<sabado>
		<data> 26/11/2011</data>
		<almoco>
			<salada>Saladas diversas</salada>
			<principal>Salsicha ao molho</principal>
			<acompanhamento>Purê de batatas</acompanhamento>
			<sobremesa>Chocolate e laranja</sobremesa>
		</almoco>
		<jantar>
			<vazio />
		</jantar>
	</sabado>
</restaurante>
